// Tiers
// 1: 5   buildings
// 2: 15  buildings
// 3: 35  buildings
// 4: 50  buildings
// 5: 75  buildings
// 6: 100 buildings
// 7: 150 buildings
// 8: 200 buildings
// 9: 250 buildings
//10: 300 buildings

import Game from "./Game";

/**
 * The benefits that are given out by an upgrade when bought.
 */
interface Benefits {
    /**
     * A function that takes in certain parameters which outputs new rates of coins generated by the building.
     */
    [key: string]: (
        coins: number,
        isCoinsPerSec: boolean,
        game: Game
    ) => number,
}

/**
 * The requirements to unlock the upgrade so that it can be bought.
 */
interface Requirements {
    /**
     * Describes how many of a particular building is required.
     */
    [key: string]: number
}

/**
 * A upgrade that exists in game.
 */
interface Upgrade {
    /**
     * The ID of the upgrade.
     */
    id: string,

    /**
     * The cost of the upgrade in coins.
     */
    cost: number,

    /**
     * The benefits caused by the upgrade.
     */
    benefits: Benefits,

    /**
     * The requirements required to buy the upgrade.
     */
    requirements: Requirements,

    /**
     * The icon of the upgrade.
     */
    icon: [number, number]
}

/**
 * Upgrades of the game (mostly for buildings)
 */
const upgrades: Upgrade[] = [
    {
        "id": "cursor_1",
        "cost": 100,
        "benefits": {
            cursor: x => x * 2
        },
        "requirements": {cursor: 5},
        "icon": [0, 1]
    },
    {
        "id": "family_1",
        "cost": 1500,
        "benefits": {
            family: x => x * 3
        },
        "requirements": {family: 5},
        "icon": [0, 2]
    },
    {
        "id": "shop_1",
        "cost": 15000,
        "benefits": {
            shop: x => x * 3
        },
        "requirements": {shop: 5},
        "icon": [0, 3]
    },
    {
        "id": "bank_1",
        "cost": 850000,
        "benefits": {
            bank: x => x * 2
        },
        "requirements": {bank: 5},
        "icon": [0, 5]
    },
    {
        "id": "carnival_1",
        "cost": 7500000,
        "benefits": {
            carnival: x => x * 2
        },
        "requirements": {carnival: 5},
        "icon": [0, 6]
    },
    {
        "id": "power_plant_1",
        "cost": 40000000,
        "benefits": {
            power_plant: x => x * 2
        },
        "requirements": {power_plant: 5},
        "icon": [0, 7]
    },
    {
        "id": "cursor_2",
        "cost": 750,
        "benefits": {
            cursor: x => x * 3
        },
        "requirements": {cursor: 15},
        "icon": [1, 1]
    },
    {
        "id": "family_2",
        "cost": 350000,
        "benefits": {
            family: x => x * 10,
            shop: (x, _, game) => x * (1 + game.getNumberOfBuildings('family') / 100)
        },
        "requirements": {family: 15},
        "icon": [1, 2]
    },
    {
        "id": "shop_2",
        "cost": 400000,
        "benefits": {
            shop: x => x * 5
        },
        "requirements": {shop: 15},
        "icon": [1, 3]
    },
    {
        "id": "bank_2",
        "cost": 7000000,
        "benefits": {
            bank: x => x * 7
        },
        "requirements": {bank: 15},
        "icon": [1, 5]
    },
    {
        "id": "carnival_2",
        "cost": 25000000,
        "benefits": {
            carnival: x => x * 3
        },
        "requirements": {carnival: 15},
        "icon": [1, 6]
    },
    {
        "id": "power_plant_2",
        "cost": 300000000,
        "benefits": {
            power_plant: x => x * 3
        },
        "requirements": {power_plant: 15},
        "icon": [1, 7]
    },
    {
        "id": "cursor_3",
        "cost": 65000,
        "benefits": {
            cursor: x => x * 8
        },
        "requirements": {cursor: 35},
        "icon": [2, 1]
    },
    {
        "id": "cursor_4",
        "cost": 4000000,
        "benefits": {
            cursor: (x, _, game) => x * (1 + game.getTotalBuildings(true) / 100)
        },
        "requirements": {cursor: 50},
        "icon": [3, 1]
    },
    {
        "id": "cursor_5",
        "cost": 35000000,
        "benefits": {
            cursor: (x, _, game) => x * (1 + game.getTotalBuildings(true) / 50)
        },
        "requirements": {cursor: 75},
        "icon": [4, 1]
    },
    {
        "id": "cursor_6",
        "cost": 200000000,
        "benefits": {
            cursor: (x, _, game) => x * (1 + game.getTotalBuildings(true) / 100 * 3)
        },
        "requirements": {cursor: 100},
        "icon": [5, 1]
    },
];

export {
    upgrades as default,
    Upgrade
};